<?php

/**
 * Major cities and towns in Pakistan (A–Z) for destination search.
 */
return [
    'Abbottabad',
    'Ahmadpur East',
    'Ahmadpur Sial',
    'Arifwala',
    'Attock',
    'Badin',
    'Bagh',
    'Bahawalnagar',
    'Bahawalpur',
    'Bannu',
    'Batkhela',
    'Bela',
    'Bhakkar',
    'Bhalwal',
    'Bhera',
    'Bhimber',
    'Burewala',
    'Chak Jhumra',
    'Chakwal',
    'Charsadda',
    'Chichawatni',
    'Chiniot',
    'Chishtian',
    'Chitral',
    'Chunian',
    'Dadu',
    'Daska',
    'Dera Ghazi Khan',
    'Dera Ismail Khan',
    'Dina',
    'Dinga',
    'Dipalpur',
    'Duniyapur',
    'Faisalabad',
    'Fateh Jang',
    'Gadoon',
    'Gambat',
    'Ghotki',
    'Gojra',
    'Gujar Khan',
    'Gujranwala',
    'Gujrat',
    'Gwadar',
    'Hafizabad',
    'Hala',
    'Hangu',
    'Haripur',
    'Hasilpur',
    'Hassan Abdal',
    'Havelian',
    'Hub',
    'Hyderabad',
    'Islamabad',
    'Jacobabad',
    'Jampur',
    'Jamshoro',
    'Jaranwala',
    'Jatoi',
    'Jauharabad',
    'Jhang',
    'Jhelum',
    'Kabirwala',
    'Kahror Pakka',
    'Kamalia',
    'Kamoke',
    'Kandhkot',
    'Kandiaro',
    'Karachi',
    'Kasur',
    'Khairpur',
    'Khanewal',
    'Khanpur',
    'Kharian',
    'Khipro',
    'Khushab',
    'Khuzdar',
    'Kohat',
    'Kot Addu',
    'Kotli',
    'Kotri',
    'Kundian',
    'Lahore',
    'Lakki Marwat',
    'Lalamusa',
    'Larkana',
    'Layyah',
    'Liaquatpur',
    'Lodhran',
    'Loralai',
    'Mailsi',
    'Mandi Bahauddin',
    'Mansehra',
    'Mardan',
    'Mastung',
    'Matli',
    'Mehrabpur',
    'Mian Channu',
    'Mianwali',
    'Mingora',
    'Mirpur',
    'Mirpur Khas',
    'Mithi',
    'Multan',
    'Muridke',
    'Murree',
    'Muzaffarabad',
    'Muzaffargarh',
    'Nankana Sahib',
    'Narowal',
    'Nasirabad',
    'Nawabshah',
    'Nowshera',
    'Okara',
    'Pakpattan',
    'Palandri',
    'Pasrur',
    'Pattoki',
    'Peshawar',
    'Pishin',
    'Qila Abdullah',
    'Quetta',
    'Rahim Yar Khan',
    'Raiwind',
    'Rajanpur',
    'Rawalakot',
    'Rawalpindi',
    'Renala Khurd',
    'Rohri',
    'Sadiqabad',
    'Sahiwal',
    'Sambrial',
    'Samundri',
    'Sanghar',
    'Sargodha',
    'Sehwan',
    'Shahdadkot',
    'Shahdadpur',
    'Shakargarh',
    'Sheikhupura',
    'Shikarpur',
    'Sialkot',
    'Sibi',
    'Skardu',
    'Sukkur',
    'Swabi',
    'Swat',
    'Talagang',
    'Tando Adam',
    'Tando Allahyar',
    'Tando Muhammad Khan',
    'Tank',
    'Taxila',
    'Thatta',
    'Timergara',
    'Toba Tek Singh',
    'Turbat',
    'Umerkot',
    'Vehari',
    'Wah Cantonment',
    'Wazirabad',
    'Zhob',
];
