<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ $invoice->invoice_number }}</title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; color:#0f172a; }
        .wrap { padding: 24px; }
        .title { font-size: 22px; font-weight: 900; letter-spacing: -0.02em; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th, td { border: 1px solid #e5e7eb; padding: 10px; font-size: 12px; }
        th { text-align: left; background: #f8fafc; }
        .num { font-weight: 900; }
        .muted { color:#64748b; }
    </style>
</head>
<body>
    <div class="wrap">
        <div class="title">{{ $invoice->invoice_number }}</div>
        <div class="muted" style="margin-top:6px; font-size:12px;">
            Period: {{ optional($invoice->period_start)->format('d M Y') }} - {{ optional($invoice->period_end)->format('d M Y') }}
        </div>

        <table>
            <tr>
                <th>Total COD</th>
                <td class="num">Rs. {{ number_format((float)$invoice->total_cod, 2) }}</td>
            </tr>
            <tr>
                <th>DC + Govt Tax (Total Deductions)</th>
                <td class="num">Rs. {{ number_format((float)$invoice->total_deductions, 2) }}</td>
            </tr>
            <tr>
                <th>Net Transferable</th>
                <td class="num">Rs. {{ number_format((float)$invoice->net_amount, 2) }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td class="num">{{ ucfirst((string)$invoice->status) }}</td>
            </tr>
            <tr>
                <th>Payment Method</th>
                <td>{{ $invoice->payment_method ?? '—' }}</td>
            </tr>
        </table>

        <div class="muted" style="margin-top:18px; font-size:11px;">
            Generated by Shah Jee Courier.
        </div>
    </div>
</body>
</html>

